### ISSUE TITLE
Clock Circle is always painted white even in dark mode . 

### ISSUE THREAD

**Issue by Aman-Malhotra** [cdharris/flutter_duration_picker#10]
The clock circle being painted in your flutter_duration_picker.dart file is _always white_ in color even when I change the brightness in ThemeData to Brightness.dark. 
In the flutter_duration_picket.dart file inside the CustomPainter class named _DialPainter
inside paint overridden function 
see this code **( Images attatched are in Brightness.dark mode )**
```
// Draw the inner background circle
    canvas.drawCircle(centerPoint, radius * 0.88,
        new Paint()..color = Colors.white); 
```
![screenshot_20181224-004628](https://user-images.githubusercontent.com/30658517/50386901-e558fc80-0716-11e9-9ccf-5f1a56c09349.png)
change this code to 
```
// Draw the inner background circle
    canvas.drawCircle(centerPoint, radius * 0.88,
        new Paint()..color = Theme.of(context).canvasColor);
```
![screenshot_20181224-004652](https://user-images.githubusercontent.com/30658517/50386902-e5f19300-0716-11e9-900a-c7c0e90b1df7.png)
so that the color of clock background depends on the theme of the app i.e if the app is in Dark theme or in Light theme( brightness in ThemeData).

**Comment by aravind816** [comment]
When this bug will be closed ?

**Comment by aravind816** [comment]
Thanks

**Comment by nohli** [comment]
So, you fixed this six months ago, but the latest package version is from eight months ago...so how are users able to easily import your package in pubspec.yaml?

**Comment by cyberpwnn** [comment]
Just paste the source code into a random file in your project and replace the line specified above, then remove the package from your pubspec.

**Comment by nohli** [comment]
@cyberpwnn thanks

Or one could add the following to pubspec.yaml dependencies (for the latest commit):


```
  flutter_duration_picker:
    git:
      url: https://github.com/cdharris/flutter_duration_picker
      ref: a44d26
```
