### ISSUE TITLE
Importing the project to Android Studio

### ISSUE THREAD

**Issue by guyhatzav** [cdharris/flutter_duration_picker#6]
hi chris,
I really liked the picker you did, I'm a bit new in the field and unable to add it to Android Studio. I'd love to get help :) 

Thanks in advance!

**Comment by cdharris** [comment]
Hi @guyhatzav, I'm not sure what you mean about importing it, could you explain a little further thanks?

This library is written solely in Dart so you'd need the Dart lang plugin for your ide to make sense of it. Maybe that helps.

**Comment by guyhatzav** [comment]
Hi @cdharris, I'm making a project in Android Studio and I want to combine the picker inside but I have not been able to do it so far. Until now I used to work with the regular implementations system (like:     implementation files('libs/joda-time-2.10.jar')). Is there a good tutorial I can use to integrate a flutter project into an existing project? 
Thanks in advance.

**Comment by cdharris** [comment]
Ah sounds like you're trying to use this library in a standard Java based android app?

Sorry I won't be able to help much there, Flutter is it's own ecosystem (SDK, build tools, etc). While it is possible to integrate a flutter project into an existing Android app, I don't imagine it would be worth the effort to do so just to use this plugin :) 

If you'd like to use Flutter instead, there's plenty of good starting docs on the flutter.io site.

Good luck with your project!
